# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Shadow
enable_shadow = false

# Set this to true if you want to use old LWJGL2 methods.
enable_lwjglx = true

# Mod Information
mod_version = 3.0.1
root_package = io.github.tehstoneman
mod_id = betterstorage
mod_name = BetterStorageToo

# Mod Metadata (Optional)
mod_description = Adds more storage related blocks and items to the game.
mod_url =
mod_update_json =
mod_authors = TehStoneMan, copygirl, Vic Nightfall
mod_credits =
mod_logo_path =

# Run Configurations
minecraft_username = Developer
extra_jvm_args =
enable_foundation_debug = false

# Maven Publishing (Provide secret: MAVEN_USER, MAVEN_PASS)
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Access Transformers
use_access_transformer = false

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
